import pandas as pd
import glob
import os

# Locate all CSVs generated by CICFlowMeter
csv_files = glob.glob("output_csv/*.csv")
print(f"Found {len(csv_files)} files to merge.")

df_list = []
for f in csv_files:
    df = pd.read_csv(f)

    # Critical: CICFlowMeter adds random spaces to its column headers.
    # This strips them so you don't get KeyError bugs later.
    df.columns = df.columns.str.strip()

    # Critical fix: tag every row with which file it came from, so we can
    # label rows later even without knowing exact attack timestamps.
    df["source_file"] = os.path.basename(f)

    df_list.append(df)

# Read and combine all files
merged_df = pd.concat(df_list, ignore_index=True)

# Save the master dataset
merged_df.to_csv("ml_ready_data.csv", index=False)
print(f"Merged dataset saved with {len(merged_df)} total flows!")
print("\nRows per source file:")
print(merged_df["source_file"].value_counts())